version: '3.7'

services:

  volume-populate: # this is just used to copy the content
    image: busybox
    command: cp -r /tmp/src/. /data
    volumes:
      - ./.docker_compose:/tmp/src:Z
      - oathkeeper-volume:/data

  oathkeeper:
    build:
      context: .
      dockerfile: Dockerfile-dc
    ports:
      - 4455:4455
      - 4456:4456
    command:
      serve --config=/etc/config/oathkeeper/config.yaml
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDER_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDER_JAEGER_SAMPLING_VALUE=1
    volumes:
      - oathkeeper-volume:/etc/config/oathkeeper
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686 # The UI port

volumes:
  oathkeeper-volume:
